# Generated by Django 3.2 on 2024-10-06 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feeds_comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=100)),
                ('likes', models.IntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Likescount',
            new_name='Feeds_likes',
        ),
        migrations.RenameField(
            model_name='feeds',
            old_name='post',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='feeds',
            name='likes',
        ),
        migrations.AddField(
            model_name='images',
            name='message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_images', to='main.messages'),
        ),
        migrations.DeleteModel(
            name='comments',
        ),
        migrations.AddField(
            model_name='feeds_comments',
            name='feed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_comment', to='main.feeds'),
        ),
        migrations.AddField(
            model_name='feeds_comments',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_comment', to='main.feeds_comments'),
        ),
        migrations.AddField(
            model_name='feeds_comments',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_commet', to=settings.AUTH_USER_MODEL),
        ),
    ]
